### ISSUE TITLE
Determine what the OS Auth server returns as access token: a signed JWT or opaque token?

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-auth#101]
Now it's a bit of both...

Proposal:
a signed JWT with a custom pri-pub key. The pub key would have to be configured at the resources server. Then the resource server only has to verify consent, auth has been done. Better separation of concerns.

**Comment by woutslakhorst** [comment]
Token introspection is then no longer required.

**Comment by reinkrul** [comment]
Could we use the registry as a means to publish the public key?

**Comment by woutslakhorst** [comment]
No this is between the auth server and resource server, out of scope for the Nuts specs

**Comment by stevenvegt** [comment]
I would like to stick to introspection. This gives a much better upgrade path and ensures that the checks are performed in a uniform and correct way. It requires less knowledge at the side of the implementor, also less key management.

**Comment by woutslakhorst** [comment]
It's not introspection, it must be a validation call. The used TLS cert must also be linked to the access token somehow.

**Comment by woutslakhorst** [comment]
validation call is always needed so this issue is no longer relevant
