### ISSUE TITLE
NilPointer when checking signing session status on irma verifier

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-auth#148]
Even when Irma is fully configured, retrieving the status for a session hits a nilpointer in the Irma verifier.
It might be due to the refactor and thus wrong initialization or it's regular behaviour for Irma.... (requesting an unknown session)

**Comment by stevenvegt** [comment]
How to reproduce?

We used the same config for bothe irma verifier and issuer. See this slack conversation for the advise from IRMA:
>Het samenvoegen van deze configuraties moet prima kunnen. De handigste strategie is dan om zelf de configuratie te injecteren in server.Configuration. De server maakt namelijk niet standaard zijn instance van irma.Configuration beschikbaar voor de buitenwereld.
Perhaps this change caused some side effects?

**Comment by woutslakhorst** [comment]
Can not reproduce
