### ISSUE TITLE
Remove legacy_auth_token

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-auth#53]
when all parties have implemented new style token:

- [x] Nedap in API gateway
- [x] CareSharing in vendor client software
- [x] Remove code

**Comment by woutslakhorst** [comment]
The difference in the auth_token and legacy_auth_token is the contents of the JWT not the fact that one is given by an oauth_flow and the other isn't. The new is does support the oauth flow though.

**Comment by stevenvegt** [comment]
@Timendus Is Demo EHR using the legacy token?

**Comment by Timendus** [comment]
I don't think it is. I used to use a crappy home-brew token, you replaced that with the new oAuth flow. We're probably good.

And otherwise, let's just move fast and break things. We'll just fix it then.
