### ISSUE TITLE
Irma configuration for validation not updated

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-auth#86]
The embedded Irma server is using auto updates, but the DefaultValidator has a static reference to the state of the configuration how it was at startup. This config must also auto-update....

A way is to have the Irma server do the download and have the configuration from the validator do a periodical reload of the scheme on disk.

**Comment by woutslakhorst** [comment]
This is also a bug in irmago (fixed in 0.5.0)

**Comment by stevenvegt** [comment]
Should be fixed by #92
