### ISSUE TITLE
Determine use of `scope` in OAuth bearer token.

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-auth#96]
The current implementation has a scope param but the Nuts OAuth spec does not. Add it to the spec or remove it from the impl?

**Comment by stevenvegt** [comment]
Scope determines the intent of the client to request access to a certain set of data. This scope should also be present in the consent. The auth-server checks the scope against the consent record. If that matches, than the resource server has to check it against the actual requested data.

**Comment by woutslakhorst** [comment]
A client must add a scope to the access token request as defined by a bolt. The AS will check this when issuing an access token. Any given scope will be present in the scope claim. The resource server can then check this against the requested resource.

**Comment by woutslakhorst** [comment]
This makes the resource server independent from the auth server

**Comment by woutslakhorst** [comment]
The resource server must already check if the TLS client cert used is a sibling of the signing certificate. This is a step that has to be done by the Nuts node. The node can then also check if the requested resource may be accessed. This no longer makes the resource server independent and makes the scope obsolete.
